POSTAGS = ["AJ", "AV", "NU", "CNJ", "DET", "J", "N", "PRP", "DN", "EN", "GN",
           "MN", "PN", "RN", "SN", "TN", "WN", "AN", "CN", "FN", "LN", "ON",
           "QN", "YN"]

SPECIAL_POSTAGS = ["V", "V-PL", "V-PF", "V-RDP"]

ALL_POSTAGS = POSTAGS + SPECIAL_POSTAGS

NOUN_MORPHS = ["L1",
               "L2-NH",
               "GEN",
               "3-PL-POSS",
               "3-SG-H-POSS",
               "3-SG-NH-POSS",
               "DEM2",
               "COM",
               "PL",
               "ERG",
               "DAT-NH",
               "L3-NH",
               "DEM",
               "PL",
               "ADV",
               "EQU",
               "1-SG-POSS",
               "1-PL-POSS",
               "L4",
               "ABS",
               "DAT-H",
               "L2-H",
               "L3-H",
               "TERM",
               "ABL",
               "2-SG-POSS",
               "2-PL-POSS",
               "COP-1-SG",
               "COP-2-SG",
               "COP-3-SG",
               "COP-1-PL",
               "COP-2-PL",
               "COP-3-PL",
               "EXCEPT"]

VERB_SUFFIX = ["1-SG-A",
               "1-SG-S",
               "1-SG-P",
               "2-SG-A",
               "2-SG-S",
               "2-SG-P",
               "3-SG-S",
               "3-SG-P",
               "3-SG-A",
               "3-SG-S-OB",
               "1-PL-A",
               "1-PL-S",
               "1-PL",
               "2-PL-A",
               "2-PL-S",
               "2-PL",
               "3-PL-S",
               "3-PL-P",
               "3-PL",
               "3-PL-A",
               "PF",
               "SUB",
               "PLEN"
               ]

VERB_PREFIX = ["NEG",
               "MOD1",
               "ANT",
               "MOD2",
               "MOD4",
               "MOD6",
               "MOD7",
               "MOD3",
               "MOD5",
               "COOR",
               "VEN",
               "VEN",
               "MID",
               "FIN",
               "FIN-LI",
               "FIN-L2",
               "FIN",
               "FIN-L2",
               "FIN"
               ]

VERB_INFIX = ["3-NH",
              "1-SG",
              "2-SG",
              "2-SG",
              "3-SG-H",
              "1-PL",
              "3-PL",
              "COM",
              "DAT",
              "TERM",
              "ABL",
              "L1",
              "LOC-OB",
              "L1-SYN",
              "L2",
              "L2",
              "L2-SYN",
              "L3",
              "1-SG-A",
              "2-SG-A",
              "3-SG-H-A",
              "3-SG-H-P",
              "3-SG-H-L3",
              "1-SG-A-OB",
              "3-SG-NH-A",
              "3-SG-NH-P",
              "3-SG-NH-L3",
              "3-PL-H-P"
              ]
